### ISSUE TITLE
Problem: Move subscriptions to organization account

### ISSUE THREAD

**Issue by georgeciubotaru** [truflation/marketplace#35]
List of Accounts

- [x] - Ankr
- [x] - Alchemy
- [x] - Lianereum (nftgo)
- [x] - DataImpulse
- [x] - bitscrunch

**Comment by georgeciubotaru** [comment]
cc @Jarryd-pretorius

**Comment by georgeciubotaru** [comment]
DataImpulse - used in `truflation-ingestors`
NFTGO - used in `truflation-ingestors`

**Comment by georgeciubotaru** [comment]
Alchemy (there are some hardcoded URLs in the website repo).

@Jarryd-pretorius Do I need to create an Alchemy account or can you invite me to the existing one?

**Comment by georgeciubotaru** [comment]
@Jarryd-pretorius Will be great to get the proxy configuration values from Joseph
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/b4a2bd5c-a52c-4bd2-81b7-308a827940be">

**Comment by Jarryd-pretorius** [comment]
which service is this for @georgeciubotaru ?

**Comment by georgeciubotaru** [comment]
@Jarryd-pretorius Was, DataImpulse, but clarified already.

**Comment by georgeciubotaru** [comment]
@Jarryd-pretorius Can you help me access the `nft.truflation.com` so I can check where the Ankr endpoints are used?

Also, provide access to Alchemy.

**Comment by Jarryd-pretorius** [comment]
> @Jarryd-pretorius Can you help me access the nft.truflation.com so I can check where the Ankr endpoints are used?
Also, provide access to Alchemy.

Log: Responded to your DM

**Comment by georgeciubotaru** [comment]
Log: Alchemy usage not found, the only usage is inside the `website` repo, but the code is not used in production.
Also, the Alchemy keys are provided by @markholdex.

So there are no issues with Alchemy.

**Comment by georgeciubotaru** [comment]
All subscriptions are moved under cto@truflation.com email account
